apiVersion: apps/v1
kind: Deployment
metadata:
  name: cilium-operator
  namespace: kube-system
  labels:
    app: cilium-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cilium-operator
  template:
    metadata:
      labels:
        app: cilium-operator
    spec:
      hostNetwork: true
      serviceAccountName: cilium-operator
      priorityClassName: system-node-critical
      nodeSelector:
        kubernetes.io/hostname: rancher-master
      tolerations:
      - operator: Exists
      containers:
      - name: cilium-operator
        image: docker.io/cilium/operator:v1.6.3
        imagePullPolicy: IfNotPresent
        resources:
          requests: {}
          limits: {}
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 3
          httpGet:
            path: /healthz
            port: 9234
            scheme: HTTP
        command:
        - cilium-operator
        args:
        - --identity-allocation-mode=crd
        env:
        - name: CILIUM_K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
