kind: ConfigMap
apiVersion: v1
metadata:
  name: local-path-provisioner-config
  namespace: kube-system
data:
  config.json: |-
    {
      "nodePathMap": [
        {
          "node": "DEFAULT_PATH_FOR_NON_LISTED_NODES",
          "paths": ["/mnt"]
        }
      ]
    }
