apiVersion: storage.k8s.io/v1
kind: StorageClass
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
metadata:
  name: local-path
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
