configInline:
  address-pools:
  - name: default
    protocol: layer2
    addresses:
    - '192.168.0.2/32'

psp:
  create: false

controller:
  tolerations:
   - operator: Exists
  nodeSelector:
    kubernetes.io/hostname: rancher-master

speaker:
  tolerations:
   - operator: Exists
