---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: longhorn-ui
  namespace: longhorn-system
  labels:
    app: longhorn-ui
spec:
  selector:
    matchLabels:
      app: longhorn-ui
  template:
    metadata:
      labels:
        app: longhorn-ui
    spec:
      serviceAccountName: longhorn
      containers:
      - name: longhorn-ui
        image: longhornio/longhorn-ui:v0.7.0
        imagePullPolicy: IfNotPresent
        resources:
          requests: {}
          limits: {}
        ports:
        - name: ui
          containerPort: 8000
        env:
        - name: LONGHORN_MANAGER_IP
          value: http://longhorn-backend:9500
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: longhorn-driver-deployer
  namespace: longhorn-system
spec:
  selector:
    matchLabels:
      app: longhorn-driver-deployer
  template:
    metadata:
      labels:
        app: longhorn-driver-deployer
    spec:
      serviceAccountName: longhorn
      initContainers:
      - name: wait-longhorn-manager
        image: longhornio/longhorn-manager:v0.7.0
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -c
        - 'while [ $(curl -m 1 -s -o /dev/null -w "%{http_code}" http://longhorn-backend:9500/v1) != "200" ]; do echo waiting; sleep 2; done'
      containers:
      - name: longhorn-driver-deployer
        image: longhornio/longhorn-manager:v0.7.0
        imagePullPolicy: IfNotPresent
        command:
        - longhorn-manager
        - -d
        - deploy-driver
        - --manager-image
        - longhornio/longhorn-manager:v0.7.0
        - --manager-url
        - http://longhorn-backend:9500/v1
        - --csi-attacher-replica-count
        - '1'
        - --csi-provisioner-replica-count
        - '1'
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
