apiVersion: storage.k8s.io/v1
kind: StorageClass
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
metadata:
  name: longhorn
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
parameters:
  numberOfReplicas: '1'
  staleReplicaTimeout: '30'
  fromBackup: ''
  baseImage: ''
